C     This file has been generated automatically by FeynRules
C     Version: 1.3.23   Date: 15. 11. 2008,    11:9
C     Used for Ht process (IPROC=204*). 
      double precision g
      common /strong/ g
      double complex gal(2)
      common /weak/ gal
      double precision dum0
      common /frdum0/ dum0
      double precision dum1
      common /frdum1/ dum1
C     Masses : 
      double precision mc,mb,mt,mta,mz,mw,mh,mhc
      common /masses/ mc,mb,mt,mta,mz,mw,mh,mhc
C     Widths : 
      double precision wt,wz,ww,wh,whc
      common /widths/ wt,wz,ww,wh,whc
C     Interactions associated with Standard_Model:
      double precision mgvx11,mgvx3,mgvx15,mgvx14,
     &mgvx21,ggt1,mgvx16,mgvx24
      common /real_coupl_standard_model/mgvx11,mgvx3,mgvx15,
     &mgvx14,mgvx21,ggt1,mgvx16,mgvx24
      double complex mgvx2,mgvx1,mgvx13,mgvx23,mgvx12,mgvx22
      common /comp_coupl_standard_model/mgvx2,mgvx1,mgvx13,mgvx23,
     &mgvx12,mgvx22
      double complex mgvx18(2),mgvx28(2),mgvx34(2),mgvx53(2),
     &mgvx59(2),mgvx25(2)
     +,mgvx31(2),mgvx17(2),mgvx19(2),mgvx20(2),mgvx37(2),
     &mgvx38(2),mgvx40(2),mgvx41(2),mgvx46(2),mgvx47(2),
     &mgvx48(2),mgvx49(2),mgvx50(2),mgvx56(2),gg(2),HMCOUP(2),HPCOUP(2)
      common /chiral_coupl_standard_model/ mgvx18,mgvx28,mgvx34,
     &mgvx53,mgvx59,mgvx25,mgvx31,mgvx17,mgvx19,mgvx20,mgvx37,
     &mgvx38,mgvx40,mgvx41,mgvx46,mgvx47
     +,mgvx48,mgvx49,mgvx50,mgvx56,gg,HMCOUP,HPCOUP
