C     This file has been generated automatically by FeynRules
C     Version: 1.3.23   Date: 15. 11. 2008,    11:9
C     External Parameters :
      double precision cabi,aewm1,gf,as,zm,ymc,ymb,ymt,ymtau,a,b
      common /external_params/ cabi,aewm1,gf,as,zm,ymc,ymb,ymt,ymtau,a,b
C     Internal Parameters :
      double precision aew,sw2,ee,cw,sw,gw,g1,v,lam,
     &muh,ytau,yc,yt,yb,sqrt2,sqrt
     +pi,psw2,pgw2,pcw2
      common /internal_params_r/ aew,sw2,ee,cw,sw,gw,g1,v,
     &lam,muh,ytau,yc,yt,yb,
     +sqrt2,sqrtpi,psw2,pgw2,pcw2
      double complex ckm11,ckm12,ckm21,ckm22,conjckm21,
     &conjckm11,conjckm22,conjc
     +km12
      common /internal_params_c/ ckm11,ckm12,ckm21,ckm22,
     &conjckm21,conjckm11,con
     +jckm22,conjckm12
